In [1]:
!pip install numpy

In [1]:
import numpy as np

In [3]:
np.zeros(3)

array([0., 0., 0.])

In [4]:
type(np.zeros(3))

numpy.ndarray

In [6]:
np.zeros((2, 3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [7]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [8]:
np.ones(5, dtype=int)

array([1, 1, 1, 1, 1])

In [10]:
np.empty((3, 3))

array([[ 2.60605835e-31, -5.21211670e-31,  1.30302917e-31],
       [-5.21211670e-31,  1.13363538e-30, -3.51817877e-31],
       [ 1.30302917e-31, -3.51817877e-31,  2.01969522e-31]])

In [11]:
np.full(3, 255)

array([255, 255, 255])

In [13]:
np.random.rand(2,5)

array([[0.24865617, 0.84216393, 0.8179425 , 0.44264779, 0.02085278],
       [0.11568614, 0.78756894, 0.45456055, 0.97893599, 0.48750745]])

In [14]:
np.random.randint(low=2, high=8, size=(2, 3), dtype=int)

array([[3, 5, 5],
       [6, 6, 2]])

In [15]:
test_arr = np.array([2, 4, 4])
test_arr

array([2, 4, 4])

In [16]:
test_arr.ndim

1

In [17]:
test_arr.shape

(3,)

In [18]:
test_arr.size

3

In [19]:
np.random.randint(low=2, high=8, size=(2, 3), dtype=int).shape

(2, 3)

In [20]:
np.random.randint(low=2, high=8, size=(2, 3), dtype=int).size

6

In [21]:
arr = np.random.randint(low=2, high=8, size=(2, 3), dtype=int)
arr

array([[5, 5, 7],
       [2, 2, 4]])

In [22]:
arr.reshape((3, 2))

array([[5, 5],
       [7, 2],
       [2, 4]])

In [23]:
arr.reshape((3, -1))

array([[5, 5],
       [7, 2],
       [2, 4]])

In [ ]:
a,1,t,7,8,5,6,9,8,1,a,1,t,7,8,5,6,9,8,1,a,1,t,7,8,5,6,9,8,1,a,1,t,7,8,5,6,9,8,1
arr.reshape((-1, 10))

In [24]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr

array([1, 2, 3, 4, 5, 6])

In [25]:
arr.mean()

3.5

In [26]:
np.mean(arr)

3.5

In [27]:
arr.max()

6

In [28]:
arr.min()

1

In [29]:
np.median(arr)

3.5

In [30]:
help(np.median)

Help on function median in module numpy:

median(a, axis=None, out=None, overwrite_input=False, keepdims=False)
    Compute the median along the specified axis.
    
    Returns the median of the array elements.
    
    Parameters
    ----------
    a : array_like
        Input array or object that can be converted to an array.
    axis : {int, sequence of int, None}, optional
        Axis or axes along which the medians are computed. The default
        is to compute the median along a flattened version of the array.
        A sequence of axes is supported since version 1.9.0.
    out : ndarray, optional
        Alternative output array in which to place the result. It must
        have the same shape and buffer length as the expected output,
        but the type (of the output) will be cast if necessary.
    overwrite_input : bool, optional
       If True, then allow use of memory of input array `a` for
       calculations. The input array will be modified by the call to
       `med

In [34]:
np.percentile(arr, 50, method='higher')
np.percentile(arr, 50, interpolation='higher')

/var/folders/bv/8bbkzq895db366kq27vw262r0000gn/T/ipykernel_19628/4201260348.py:2: DeprecationWarning: the `interpolation=` argument to percentile was renamed to `method=`, which has additional options.
Users of the modes 'nearest', 'lower', 'higher', or 'midpoint' are encouraged to review the method they used. (Deprecated NumPy 1.22)
  np.percentile(arr, 50, interpolation='higher')


4

In [32]:
help(np.percentile)

Help on function percentile in module numpy:

percentile(a, q, axis=None, out=None, overwrite_input=False, method='linear', keepdims=False, *, interpolation=None)
    Compute the q-th percentile of the data along the specified axis.
    
    Returns the q-th percentile(s) of the array elements.
    
    Parameters
    ----------
    a : array_like
        Input array or object that can be converted to an array.
    q : array_like of float
        Percentile or sequence of percentiles to compute, which must be between
        0 and 100 inclusive.
    axis : {int, tuple of int, None}, optional
        Axis or axes along which the percentiles are computed. The
        default is to compute the percentile(s) along a flattened
        version of the array.
    
        .. versionchanged:: 1.9.0
            A tuple of axes is supported
    out : ndarray, optional
        Alternative output array in which to place the result. It must
        have the same shape and buffer length as the expect

In [35]:
arr

array([1, 2, 3, 4, 5, 6])

In [36]:
arr * 2

array([ 2,  4,  6,  8, 10, 12])

In [37]:
arr + 10

array([11, 12, 13, 14, 15, 16])

### 標準差  $\sigma = \sqrt{\frac{1}{n} \sum_{i=1}^n (x_i-\mu)^2}$


In [38]:
mu = arr.mean()

In [39]:
arr - mu

array([-2.5, -1.5, -0.5,  0.5,  1.5,  2.5])

In [40]:
arr.sum()

21

In [42]:
(arr - mu).mean()

0.0

In [43]:
np.power((arr - mu), 2)

array([6.25, 2.25, 0.25, 0.25, 2.25, 6.25])

In [44]:
np.power((arr - mu), 2).mean()

2.9166666666666665

In [45]:
np.sqrt(
    np.power(
        (arr - mu), 2
    ).mean()
)

1.707825127659933

In [46]:
arr.std()

1.707825127659933

In [47]:
np.random.normal(0, 1, 10)

array([-0.48158653,  0.24133623,  0.73231824,  1.75281579, -0.44089239,
        2.53896169, -0.53309834,  0.97387092, -0.75118391,  0.75791025])

In [48]:
arr

array([1, 2, 3, 4, 5, 6])

In [49]:
arr > 3

array([False, False, False,  True,  True,  True])

In [50]:
~(arr > 3)

array([ True,  True,  True, False, False, False])

In [52]:
arr > 2

array([False, False,  True,  True,  True,  True])

In [53]:
arr < 5

array([ True,  True,  True,  True, False, False])

In [54]:
(arr > 2) & (arr < 5)

array([False, False,  True,  True, False, False])

In [55]:
set([3, 4, 5, 6])

{3, 4, 5, 6}

In [56]:
set([1, 2, 3, 4])

{1, 2, 3, 4}

In [57]:
set([3, 4, 5, 6]) & set([1, 2, 3, 4])

{3, 4}

In [58]:
set([3, 4, 5, 6]) | set([1, 2, 3, 4])

{1, 2, 3, 4, 5, 6}

In [59]:
set([3, 4, 5, 6]) - set([1, 2, 3, 4])

{5, 6}

In [60]:
(arr > 2) | (arr < 5)

array([ True,  True,  True,  True,  True,  True])

In [61]:
(arr > 2) ^ (arr < 5)

array([ True,  True, False, False,  True,  True])

In [62]:
(arr > 2) & (arr < 5)

array([False, False,  True,  True, False, False])

In [63]:
~(arr > 2) & ~(arr < 5)

array([False, False, False, False, False, False])